### ISSUE TITLE
Diagram being referenced without being drawn

### ISSUE THREAD

**Issue by Matthieu-Malyga** [imposters-handbook/sample-code#12]
Hi Rob,

in the Machinery > Markov Chains chapter of the book, you are referencing "the above diagram" but there isn't any.

« In the above diagram, each orange circle is a “state” and the arrows dictate transitions possible between each state. Except for 1 and 10, the only transitions possible at any state along the chain is the next direct state or the one prior. Notice also that none of the states allo »

Extrait de: Rob Conery. « The Imposter's Handbook. » Apple Books.

**Comment by BryanNilsen** [comment]
Rob,
Same issue for me as of February 7, 2021. 

“in the Machinery > Markov Chains chapter of the book, you are referencing "the above diagram" but there isn't any.”

This omission is in the PDF ebook version.

**Comment by ghost** [comment]
Can confirm it is in the epub version as well

**Comment by robconery** [comment]
Cheers - just about done with the next drop. Should be done in a few weeks. 
![image](https://user-images.githubusercontent.com/78586/116183994-c4808780-a6d3-11eb-90c2-3979c6b38e8b.png)

**Comment by robconery** [comment]
Fixed with next release
