### ISSUE TITLE
Chapter on automation jekyll post

### ISSUE THREAD

**Issue by OscarRobertRodriguez** [imposters-handbook/sample-code#4]
I feel like this chapter doesn't explain shell script very well your assuming too much on what people already know. I read it over several times and still do not know how I would automate it and get it running and the previous chapter were you mention oh my zsh you say to install it but then you don't go into much depth on how to to use it with scripts. 

Then you talk about linking it with dropbox but you don't show how its useful or give examples or you don't show how to revert those changes.

**Comment by robconery** [comment]
Yeah the entire chapter has been cut. I think I'll turn it into a series of blog posts. Closing this as it's been addressed.
