### ISSUE TITLE
Broken Link To This Repo

### ISSUE THREAD

**Issue by ghost** [imposters-handbook/sample-code#7]
Hello!

It appears the link is broken to this repo in your book preview and possibly the full book(see screenshot from your preview). It points to `https//github.com/imposters-handbook/sample-code` which is missing the colon after https and doesn't route. The link should be `https://github.com/imposters-handbook/sample-code`.

![broken_link](https://user-images.githubusercontent.com/8486998/35620464-3b89b506-06bc-11e8-89e1-9a7784642dc3.png)

**Comment by opello** [comment]
I just noticed this as well, on page 270.

> You can find the code used in parts of this section up at my github repo. In addition, you can buy 17 video walkthroughs of the patterns you see in this chapter and others from here.

For me, in Acrobat Reader DC, "github repo" links to `http://https://github.com/imposters-handbook/sample-code/tree/master/algorithms`.  The "you can buy 17 video walkthroughs" links to `https://goo.gl/2XZCHc`, which is valid and works.  But the "from here" after it is broken too:  `http://https://goo.gl/2XZCHc`.

Given [the recent announcement from Google][1] it might be worth picking a different service or hosting your own specifically for the book links.

[1]: https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

**Comment by robconery** [comment]
Thanks - I had an issue with doubled up "http" that looks like I didn't fix all of.

**Comment by robconery** [comment]
Fixed with next release
