### ISSUE TITLE
A couple of issues on the recursive Fibonacci demonstration

### ISSUE THREAD

**Issue by ghost** [imposters-handbook/sample-code#8]
In the example that shows how 'bad' the recursive calculation of Fib numbers is (_fib.js_), shouldn't the `fibCount` variable be reset to zero for each iteration of the loop?
Right now it accumulates the calls of previous calculations of the loop, not only the previous recursive calls.

Instead of this:
```
var fibCount=0;
var calculateFibAt = function(n){
  fibCount = fibCount+1;
  ...
}

for(var i = 0; i<=10; i++){
  var fib = calculateFibAt(i);
  ...
}
```

Shouldn't it be like this:
```
var fibCount=0;
var calculateFibAt = function(n){
  fibCount = fibCount+1;
  ...
}

for(var i = 0; i<=10; i++){

  fibCount=0; // this has been added

  var fib = calculateFibAt(i);
  ...
}
```

---

Apart from this, `var calc;` on line 17 of _fib.js_ doesn't seem to be used.

**Comment by robconery** [comment]
I don't know if I follow what problem you're seeing and what you expect to see. There *is* a weirdness in one of the examples where `fibCount` is there but shouldn't be. Aside from that, when it is supposed to be used it's a counter to show how many times `calculateFibAt` is called.

So... what's the issue?

**Comment by ghost** [comment]
Yes, but shouldn't that counter be reset to zero for each iteration of the `for` loop?

In the code as it is now, it accumulates the counts of previous calculations of the loop not related to that iteration. For example, for position 2 it says:

`The Fibonacci number at position 2 is 1; It took 5 calls to fib to get here`

In reality `calculateFibAt(2)` only took 3 calls to fib (calculateFibAt(2), calculateFibAt(1) and calculateFibAt(0)), but it displays 5 instead, because fibCount was not set to zero before the initial call.

Excuse me if I'm not being clear enough or I am missing something :)

**Comment by robconery** [comment]
That's the intention: I want every call to `calculateFibAt` counted.

>In reality calculateFibAt(2) only took 3 calls to fib (calculateFibAt(2), calculateFibAt(1) and calculateFibAt(0)),

I don't know what "reality" you're referring to. Computers don't tell fictional stories so help me understand what you expect to see.

**Comment by ghost** [comment]
If you didn't use the for loop as an example and instead you made a few calls to the function manually, printing the number of calls for each one separately, those numbers would be different, right?

If instead of this:
```
for(var i = 0; i<=10; i++){
  var fib = calculateFibAt(i);
  console.log...
}
``` 

you did this:
```
fibCount=0;
fib = calculateFibAt(0);
console.log...

fibCount=0;
fib = calculateFibAt(1);
console.log...

fibCount=0;
fib = calculateFibAt(2);
console.log...
```

You would see:
```
The Fibonacci number at position 0 is 0; It took 1 calls to fib to get here
The Fibonacci number at position 1 is 1; It took 1 calls to fib to get here
The Fibonacci number at position 2 is 1; It took 3 calls to fib to get here
```

Notice the call counts are 1,1,3 instead of 1,2,5. This is because it only counts the calls for each calculation separately. I can't see why it would be desirable to count the absolute total of calls made instead, so that's why I thought this was an issue.

That is what I was expecting to see. Maybe it's not what you wanted and the code in the example is right.

**Comment by robconery** [comment]
Ah - thanks, I think I understand the problem :). Let's see...

We're trying to calculate FIb numbers up to a given *position*. The `calculateFibAt` function will only tell you what the fibonacci number is in the *nth* position, which is not what the interviewer asked for. They asked for a list:

> How would you derive a Fibonacci sequence up to a given position?

To create the list (which is a list of Fibonacci numbers at nth position) we need to execute a loop. That, I think, is the thing that's bugging you. If I was only interested in calculations for each position, yes, resetting the counter would make sense. I'm interested in how many times it takes for *the whole operation*.

Does that help?

**Comment by ghost** [comment]
Wow, right. I was totally missing that point. Then the code is completely fine.

Thanks for the clarification! And thanks for the book as well! :)

**Comment by robconery** [comment]
You're welcome - it's funny as I was reading it over I was like "yeah... why did i do that...?" Easy thing to think :).
